FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && \
    apt-get install -y build-essential \
        libgl1 \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
        libxcb1 \
        libx11-6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install docling

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .